### ISSUE TITLE
Not Working on XZ1 CarbonROM 8 (Android Q)

### ISSUE THREAD

**Issue by TuxNews** [kitsunyan/foxy-boot#10]
![photo_2020-06-11_15-02-08](https://user-images.githubusercontent.com/45686773/84388252-8a5de280-abf4-11ea-818a-4e34eed7967e.jpg)

Not working.

**Comment by kitsunyan** [comment]
Duplicate of https://github.com/kitsunyan/foxy-boot/issues/8.
