### ISSUE TITLE
Can't install on my Samsung A50 Android 10

### ISSUE THREAD

**Issue by VersaceVeCe** [kitsunyan/foxy-boot#12]
![Screenshot_20200701-223335](https://user-images.githubusercontent.com/67631696/86279400-01323e00-bbeb-11ea-9db1-f3a297438a13.jpg)
I was able to install the module, and now I can't. Why?

**Comment by kitsunyan** [comment]
Yes, known issue. https://github.com/kitsunyan/foxy-boot/issues/8

>  I was able to install the module, and now I can't. Why?

Because of Android 10 update, I think.

**Comment by kinesight** [comment]
> ![Screenshot_20200701-223335](https://user-images.githubusercontent.com/67631696/86279400-01323e00-bbeb-11ea-9db1-f3a297438a13.jpg)
> I was able to install the module, and now I can't. Why? 

Its an Android 10 thing, the developer of the module didn't update it for 10. I am was also sad last week when I updated and tried flashing this module.

**Comment by kinesight** [comment]
> ![Screenshot_20200701-223335](https://user-images.githubusercontent.com/67631696/86279400-01323e00-bbeb-11ea-9db1-f3a297438a13.jpg)
> I was able to install the module, and now I can't. Why? 

If you're interested in an Alternative, there's an app called LiveBoot Available on Playstore, it uses Root.
