### ISSUE TITLE
Magisk support for Android 8.0 and higher

### ISSUE THREAD

**Issue by SachinKarinki** [kitsunyan/foxy-boot#2]
- Copying zip to temp directory
- Installing Foxy_Boot-1.1.zip
- Mounting /system, /vendor
Archive:  /data/user/0/com.Qgh5SByCji.Y1w.q/cache/install.zip
  inflating: service.sh
  inflating: install.sh
  inflating: module.prop
*******************************
           Foxy Boot           
*******************************
******************************
Powered by Magisk (@topjohnwu)
******************************
- Checking Android version
! Boot animation cannot be replaced with Magisk on Android 8.0 and higher!
! Installation failed

**Comment by kitsunyan** [comment]
It doesn't work since bootanimation is started before post-fs-data stage on Android 8 and higher. Magisk performs mounts at post-fs-data and replaces the bootanimation too late.

**Comment by mathew2214** [comment]
could this be made to function on android 8 and newer if it was completely independent of magisk?

**Comment by kitsunyan** [comment]
@mathew2214 [here](https://github.com/kitsunyan/foxy-boot/issues/1#issuecomment-483005786) is an explanation how to make it work on Android 8. You need to place the binary to `/system/bin/bootanimaion`, set permissions, and then edit selinux policy to allow bootanimation access the kernel ring buffer.

**Comment by zzndb** [comment]
After @kitsunyan fix ABI compatibility with Android 9 myself replace binary work fine with a self magisk module which just edit selinux policy using foxy-boot's service.sh file. Thanks @kitsunyan awesome job!

**Comment by kitsunyan** [comment]
@flameshikari hi! I noticed you forked the code and removed Android version check. Which Android version do you have? Do you use encryption?

**Comment by flameshikari** [comment]
@kitsunyan hello! I use Oreo, no encryption. The module without version checking works fine, under Pie too.

**Comment by kitsunyan** [comment]
I also noticed that it works for my friend with Android 8. There could be problems when encryption is used, I guess.

I removed the check so foxy boot was available for anybody, but I can't guarantee that it will 100% work for anybody until I come up with solution.

**Comment by apnof** [comment]
Hi, running Android 8.1.0 on BQ Aquaris X Pro (http://www.gsmarena.com/bq_aquaris_x_pro-8641.php) with Magisk 19.1.
When activating the module, the phone boots with the stock bootanimation.

**Comment by 6stR2** [comment]
Works for me right out of box on encrypted pie (AOSPex, magisk 19.2)

**Comment by Masamune3210** [comment]
Works fine for me on a OnePlus 6t running OxygenOS Pie

**Comment by kitsunyan** [comment]
@apnof check [this thread](https://github.com/kitsunyan/foxy-boot/issues/5) please, especially the suggestion in [this comment](https://github.com/kitsunyan/foxy-boot/issues/5#issuecomment-495656289).

**Comment by Ristovski** [comment]
~~On LOS16.1 (Pie) the stock bootanimation runs, but if one triggers a soft restart then foxy-boot appears. Any explanation?~~

EDIT: Works when using service script from https://github.com/kitsunyan/foxy-boot/issues/5#issuecomment-495656289, albeit there's a delay before foxy-boot starts, thus roughly ~1s of the stock bootanimation is visible.
