### ISSUE TITLE
Not issue, but a request

### ISSUE THREAD

**Issue by mysticblaze347** [kitsunyan/foxy-boot#6]
(As title says)... Request for : I seen that Changing colors is possible, but I was wondering if and or how you could do a transparent background? Ex: Being able to see another boot animation underneath as this would be an overlay.

**Comment by kitsunyan** [comment]
Foxy boot completely replaces the bootanimation so there is nothing to display behind.

**Comment by mysticblaze347** [comment]
Now that you mention a "replacement of" it makes more sense now. Thank you
for work and reply.
